feat: add option to change api description and version
completecoding/serverless-auto-swagger pull request #99
Opened 2022-10-19 19:11 UTC by achamwada

2022-10-20 17:04 UTC, bfaulk96 commented on src/ServerlessAutoSwagger.ts
> +      description: '',
I would think it would be safer to default to no description, right?
```suggestion
```

2022-10-20 17:06 UTC, bfaulk96 commented on README.md
> +| `description`             | String to overwrite the project description with a custom one                                                         | Serverless service description
For default, `- `

2022-10-20 17:06 UTC, bfaulk96 commented on README.md
> +| `version`                 | String to overwrite the project version with a custom one                                                             | Serverless service version
For default, `1`

2022-10-20 17:07 UTC, bfaulk96 requested changes
Looks good to me other than those 3 small changes!

Thanks for contributing!

2022-10-20 17:48 UTC, achamwada commented on README.md
> +| `description`             | String to overwrite the project description with a custom one                                                         | Serverless service description
Updated

2022-10-21 16:29 UTC, bfaulk96 approved these changes

2022-10-21 17:10 UTC, merged

2022-10-21 18:58 UTC, bfaulk96 commented
@achamwada this is released and available in [v2.10.0](https://github.com/completecoding/serverless-auto-swagger/releases/tag/v2.10.0) 😄 Thanks again for the contributions1